supported_languages:
  - python
  - java


plugins:
  python:
    enable: true
    description: Generating source code on Python Language
    clazz: class_desc_gen.plugins.python_autogen.plugin.PythonAutoGenPlugin
    output_dir_name: PYTHON_AUTOGEN

  java:
    enable: true
    description: Generating source code on Java language
    clazz: class_desc_gen.plugins.java_autogen.plugin.JavaAutoGenPlugin
    output_dir_name: JAVA_AUTOGEN
