attributes:
  json_serializable:
    python:
      autogen_function: attribute_system.attributes_autogen_functions.python.json_serializable_function
      import_function: attribute_system.attributes_import_functions.python.json_serializable_import_function
    java:
      autogen_function: attribute_system.attributes_autogen_functions.java.json_serializable_function

  json_deserializable:
    python:
      autogen_function: attribute_system.attributes_autogen_functions.python.json_deserializable_function
      import_function: attribute_system.attributes_import_functions.python.json_deserializable_import_function
    java:
      autogen_function: attribute_system.attributes_autogen_functions.java.json_deserializable_function

  category:
    python:
      autogen_function: attribute_system.attributes_autogen_functions.python.category_function
      import_function: attribute_system.attributes_import_functions.python.category_import_function
    java:
      autogen_function: attribute_system.attributes_autogen_functions.java.category_function
